### ISSUE TITLE
Disable CSS handling completely

### ISSUE THREAD

**Issue by willwach** [NightWhistler/HtmlSpanner#41]
Many thanks for this fantastic lib.

I got a problem disabling CSS parsing.
I'm setting setAllowStyling(false) and setUseColoursFromStyle(false), but in log it is writing "Looking for matching CSS rules for node".

Is there a flag where i can disable css parsing completely?

**Comment by NightWhistler** [comment]
CSS parsing is in fact disabled with those options.

Basically, HtmlSpanner needs to know how to display nodes, so it will look for style information and if none is found it will fall back to the default style. The styling options simply prevent the library from actually reading and parsing the CSS tree so that in effect you will always fall back on the default style. This is because the parsing and compiling of the CSS file is by far the most expensive operation. The lookup is almost a no-op.
